---
# Author: pki 
# Version: 2025-01-31
- hosts: localhost 
  connection: local
  become: true
  
  vars:
    username: pki
    ansible_user: pki
    base_pkgs:
        - htop
        - thefuck
    desktop_pkgs:
        - v4l-utils 
        - v4l_compat 
        - webcamd
        - pwcview
        - ungoogled-chromium
        - audacity
    multimedia_pkgs:
        - mpv
        - shotcut
        - ffmpeg
  tasks:

     - name: Show the IP address
       debug:
          msg: "The hostname is {{ inventory_hostname }} and the IP is {{ansible_default_ipv4.address }}"
     - name: Install base packages
       pkgng:
        name: "{{ base_pkgs }}"
        state: present

     - name: Install desktop packages
       pkgng:
        name: "{{ desktop_pkgs }}"
        state: present

     - name: Install multimedia packages
       pkgng:
        name: "{{ multimedia_pkgs }}"
        state: present

     - name: add ansible-pull cron job
       cron:
        name: ansible auto-provision
        user: "{{ ansible_user }}"
        minute: "*/5"
        job: ansible-pull -o -U http://gitlab.dc.int/pki/freebsd-conf.git > /dev/null 2>&1

     - name: Change shell to bash 
       become: yes
       command: "chsh -s /usr/local/bin/bash {{ username }}"

     - name: add user to webcam group
       become : yes
       command: "pw groupmod webcamd -m {{ username }}"


     - name: Start on reboot
       service: name=pf enabled=yes
     - name: Copy pf.conf
       copy:
          src: ../files/pf.conf
          dest: /etc/pf.conf
          mode: 0600
     - name: Start pf now
       service: name=pf state=started

     - name: copy qtile config
       copy:
         src: ../files/config.py
         dest: "/home/{{ username }}/.config/qtile/config.py"
         mode: 0600
         force: yes

