---
# Author: pki 
# 
 
- hosts: localhost 
  connection: local
  become: true

  roles:
  - role: ntpd
  
  vars:
    fileversion: "1.11"
    username: pki
    ansible_user: pki
    base_pkgs:
        - htop
        - thefuck
        - btop
    desktop_pkgs:
        - bash
        #- v4l-utils 
        #- v4l_compat 
        #- webcamd
        #- pwcview
        #- ungoogled-chromium
        #- audacity
        #- mpv
        #- shotcut
        #- ffmpeg
    
  tasks:

     - name: Show the IP address
       debug:
          msg: "The ansible version is {{fileversion}}.\nThe hostname is {{ inventory_hostname }} and the IP is {{ansible_default_ipv4.address }}"

     - name: Install base packages
       pkgng:
        name: "{{ base_pkgs }}"
        state: present

     - name: Install desktop packages
       pkgng:
        name: "{{ desktop_pkgs }}"
        state: present

     - name: add ansible-pull cron job
       cron:
        name: ansible auto-provision
        user: "{{ ansible_user }}"
        minute: "*/10"
        job: ansible-pull -o -U http://gitlab.dc.int/pki/freebsd-conf.git > /dev/null 2>&1

     - name: Change shell to bash 
       become: yes
       command: "chsh -s /usr/local/bin/bash {{ username }}"

     - name: Start on reboot
       service: name=pf enabled=yes
     - name: Copy pf.conf
       copy:
          src: ../files/pf.conf
          dest: /etc/pf.conf
          mode: 0600

     - name: Start pf now
       service: name=pf state=started





     - name: Disable sendmail
       community.general.sysrc:
              name: sendmail_enable
              value: NONE

     - name: Configure OS to use dma
       ansible.builtin.template:
              src: mailer.conf
              dest: /etc/mail/mailer.conf
              mode: "0644"

     - name: Create periodic.conf
       ansible.builtin.copy:
              content: ""
              dest: /etc/periodic.conf
              force: false
              owner: root
              group: wheel
              mode: "0644"

     - name: Disable sendmail specific periodic configuration
       ansible.builtin.lineinfile:
              path: /etc/periodic.conf
              line: "{{ item }}"
       loop:
              - daily_clean_hoststat_enable="NO"
              - daily_status_mail_rejects_enable="NO"
              - daily_status_include_submit_mailq="NO"
              - daily_submit_queuerun="NO"

     - name: Configure dma.conf
       ansible.builtin.template:
              src: dma.conf
              dest: /etc/dma/dma.conf
              owner: root
              group: wheel
              mode: "0644"

     - name: Configure auth.conf
       ansible.builtin.template:
              src: auth.conf
              dest: /etc/dma/auth.conf
              owner: root
              group: mail
              mode: "0640"

     - name: Create alias for root
       ansible.builtin.lineinfile:
              path: /etc/mail/aliases
              line: "root: {{ dma_target_email }}"
       notify:
              - Run newaliases
