---
# Author: pki 
# Version: 0.1  
- hosts: neocortex 
  connection: local
  become: true
  
  vars:
    username: pki
    base_pkgs:
        - htop
    desktop_pkgs:
        - cmatrix
        
  tasks:

    - name: Install base packages
      pkgng:
        name: "{{ base_pkgs }}"
        state: present
        update_cache: no 

    - name: Install desktop packages
      pkgng:
        name: "{{ desktop_pkgs }}"
        state: present
        update_cache: no 

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: "{{ ansible_user }}"
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/fredrik-hansen/freebsd-conf.git > /dev/null 2>&1

    - name: Change shell to bash 
      become: yes
      command: "chsh -s /usr/bin/bash {{ username }}"

